difference(){
    import("sprocket.stl");
    cylinder(h=9,d=8);
}
    intersection(){
        translate([0,0,0]){
            cylinder(h=9,d=5.1);
        }
        translate([-10,2.1,0]){
            cube([20,10,16]);
        }
    }
    difference(){
        cylinder(h=9,d=9);
        translate([0,0,-1]){
            cylinder(h=11,d=5.1);
        }
}
